/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookingEntry {
  'id' : bigint,
  'status' : BookingStatus,
  'destination' : string,
  'surprisePlanCode' : [] | [string],
  'cancellationReason' : [] | [string],
  'userId' : string,
  'days' : bigint,
  'createdAt' : bigint,
  'totalCost' : number,
  'travelers' : bigint,
  'cancelledAt' : [] | [bigint],
  'bookingType' : string,
  'paymentRef' : string,
  'startDate' : string,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export interface BudgetEntry {
  'id' : bigint,
  'userId' : string,
  'date' : string,
  'createdAt' : bigint,
  'description' : string,
  'currency' : string,
  'category' : string,
  'amount' : number,
}
export interface CancellationResult {
  'refundAmount' : number,
  'refundPercentage' : bigint,
  'message' : string,
  'success' : boolean,
}
export interface CurrencyRateCache {
  'lastUpdated' : bigint,
  'rates' : Array<[string, number]>,
}
export interface Destination {
  'id' : string,
  'region' : string,
  'country' : string,
  'name' : string,
  'tags' : Array<string>,
  'pricePerPerson' : number,
  'description' : string,
  'image' : string,
}
export interface NotificationHistory {
  'id' : bigint,
  'destination' : string,
  'bookingId' : bigint,
  'userId' : string,
  'firedAt' : bigint,
  'reminderType' : string,
  'message' : string,
}
export interface NotificationPreference {
  'destination' : string,
  'bookingId' : bigint,
  'remind7Days' : boolean,
  'userId' : string,
  'travelDate' : string,
  'remind3Days' : boolean,
  'remind1Day' : boolean,
}
export interface Review {
  'id' : bigint,
  'userName' : string,
  'userId' : string,
  'createdAt' : bigint,
  'text' : string,
  'placeId' : string,
  'rating' : bigint,
}
export interface SurprisePlanEntry {
  'destination' : string,
  'code' : string,
  'cost' : number,
  'days' : bigint,
  'occasion' : string,
  'itinerary' : Array<string>,
  'decorations' : Array<string>,
}
export interface _SERVICE {
  'cancelBooking' : ActorMethod<[bigint, string], CancellationResult>,
  'clearNotificationHistory' : ActorMethod<[string], undefined>,
  'createBooking' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      bigint,
      string,
      number,
      string,
      [] | [string],
    ],
    bigint
  >,
  'deleteBudgetEntry' : ActorMethod<[bigint], boolean>,
  'fetchAndCacheCurrencyRates' : ActorMethod<[], undefined>,
  'getBooking' : ActorMethod<[bigint], [] | [BookingEntry]>,
  'getCurrencyRates' : ActorMethod<[], [] | [CurrencyRateCache]>,
  'getDestination' : ActorMethod<[string], [] | [Destination]>,
  'getNotificationHistory' : ActorMethod<[string], Array<NotificationHistory>>,
  'getNotificationPreferences' : ActorMethod<
    [string],
    Array<NotificationPreference>
  >,
  'getReviewsForPlace' : ActorMethod<[string], Array<Review>>,
  'getUserBudgetEntries' : ActorMethod<[string], Array<BudgetEntry>>,
  'getUserProfile' : ActorMethod<
    [bigint],
    [] | [
      {
        'name' : string,
        'createdAt' : bigint,
        'email' : string,
        'lastLogin' : bigint,
      }
    ]
  >,
  'getUserSalt' : ActorMethod<[string], [] | [string]>,
  'initDestination' : ActorMethod<
    [string, string, string, string, Array<string>, number, string, string],
    undefined
  >,
  'initSurprisePlan' : ActorMethod<
    [string, string, string, number, bigint, Array<string>, Array<string>],
    undefined
  >,
  'listAllDestinations' : ActorMethod<[], Array<Destination>>,
  'listUserBookings' : ActorMethod<[string], Array<BookingEntry>>,
  'logNotificationFired' : ActorMethod<
    [string, bigint, string, string, string],
    bigint
  >,
  'loginUser' : ActorMethod<
    [string, string],
    { 'ok' : { 'userId' : string, 'name' : string, 'email' : string } } |
      { 'err' : string }
  >,
  'registerUser' : ActorMethod<
    [string, string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'saveBudgetEntry' : ActorMethod<
    [string, string, string, number, string, string],
    bigint
  >,
  'saveNotificationPreference' : ActorMethod<
    [string, bigint, string, string, boolean, boolean, boolean],
    bigint
  >,
  'saveReview' : ActorMethod<[string, string, string, bigint, string], bigint>,
  'searchDestinations' : ActorMethod<[string], Array<Destination>>,
  'updateCurrencyRates' : ActorMethod<
    [Array<[string, number]>, bigint],
    undefined
  >,
  'validateSurprisePlanCode' : ActorMethod<[string], [] | [SurprisePlanEntry]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];