/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CancellationResult = IDL.Record({
  'refundAmount' : IDL.Float64,
  'refundPercentage' : IDL.Nat,
  'message' : IDL.Text,
  'success' : IDL.Bool,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const BookingEntry = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'destination' : IDL.Text,
  'surprisePlanCode' : IDL.Opt(IDL.Text),
  'cancellationReason' : IDL.Opt(IDL.Text),
  'userId' : IDL.Text,
  'days' : IDL.Nat,
  'createdAt' : IDL.Int,
  'totalCost' : IDL.Float64,
  'travelers' : IDL.Nat,
  'cancelledAt' : IDL.Opt(IDL.Int),
  'bookingType' : IDL.Text,
  'paymentRef' : IDL.Text,
  'startDate' : IDL.Text,
});
export const CurrencyRateCache = IDL.Record({
  'lastUpdated' : IDL.Int,
  'rates' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
});
export const Destination = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Text,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'pricePerPerson' : IDL.Float64,
  'description' : IDL.Text,
  'image' : IDL.Text,
});
export const NotificationHistory = IDL.Record({
  'id' : IDL.Nat,
  'destination' : IDL.Text,
  'bookingId' : IDL.Nat,
  'userId' : IDL.Text,
  'firedAt' : IDL.Int,
  'reminderType' : IDL.Text,
  'message' : IDL.Text,
});
export const NotificationPreference = IDL.Record({
  'destination' : IDL.Text,
  'bookingId' : IDL.Nat,
  'remind7Days' : IDL.Bool,
  'userId' : IDL.Text,
  'travelDate' : IDL.Text,
  'remind3Days' : IDL.Bool,
  'remind1Day' : IDL.Bool,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'userName' : IDL.Text,
  'userId' : IDL.Text,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'placeId' : IDL.Text,
  'rating' : IDL.Nat,
});
export const BudgetEntry = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'currency' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const SurprisePlanEntry = IDL.Record({
  'destination' : IDL.Text,
  'code' : IDL.Text,
  'cost' : IDL.Float64,
  'days' : IDL.Nat,
  'occasion' : IDL.Text,
  'itinerary' : IDL.Vec(IDL.Text),
  'decorations' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'cancelBooking' : IDL.Func([IDL.Nat, IDL.Text], [CancellationResult], []),
  'clearNotificationHistory' : IDL.Func([IDL.Text], [], []),
  'createBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteBudgetEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'fetchAndCacheCurrencyRates' : IDL.Func([], [], []),
  'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(BookingEntry)], ['query']),
  'getCurrencyRates' : IDL.Func([], [IDL.Opt(CurrencyRateCache)], ['query']),
  'getDestination' : IDL.Func([IDL.Text], [IDL.Opt(Destination)], ['query']),
  'getNotificationHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(NotificationHistory)],
      ['query'],
    ),
  'getNotificationPreferences' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(NotificationPreference)],
      ['query'],
    ),
  'getReviewsForPlace' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'getUserBudgetEntries' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BudgetEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Opt(
          IDL.Record({
            'name' : IDL.Text,
            'createdAt' : IDL.Int,
            'email' : IDL.Text,
            'lastLogin' : IDL.Int,
          })
        ),
      ],
      ['query'],
    ),
  'getUserSalt' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'initDestination' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Float64,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'initSurprisePlan' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'listAllDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
  'listUserBookings' : IDL.Func([IDL.Text], [IDL.Vec(BookingEntry)], ['query']),
  'logNotificationFired' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'loginUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'userId' : IDL.Text,
            'name' : IDL.Text,
            'email' : IDL.Text,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'saveBudgetEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveNotificationPreference' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'saveReview' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'searchDestinations' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Destination)],
      ['query'],
    ),
  'updateCurrencyRates' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)), IDL.Int],
      [],
      [],
    ),
  'validateSurprisePlanCode' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SurprisePlanEntry)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CancellationResult = IDL.Record({
    'refundAmount' : IDL.Float64,
    'refundPercentage' : IDL.Nat,
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const BookingEntry = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'destination' : IDL.Text,
    'surprisePlanCode' : IDL.Opt(IDL.Text),
    'cancellationReason' : IDL.Opt(IDL.Text),
    'userId' : IDL.Text,
    'days' : IDL.Nat,
    'createdAt' : IDL.Int,
    'totalCost' : IDL.Float64,
    'travelers' : IDL.Nat,
    'cancelledAt' : IDL.Opt(IDL.Int),
    'bookingType' : IDL.Text,
    'paymentRef' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const CurrencyRateCache = IDL.Record({
    'lastUpdated' : IDL.Int,
    'rates' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  });
  const Destination = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Text,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'pricePerPerson' : IDL.Float64,
    'description' : IDL.Text,
    'image' : IDL.Text,
  });
  const NotificationHistory = IDL.Record({
    'id' : IDL.Nat,
    'destination' : IDL.Text,
    'bookingId' : IDL.Nat,
    'userId' : IDL.Text,
    'firedAt' : IDL.Int,
    'reminderType' : IDL.Text,
    'message' : IDL.Text,
  });
  const NotificationPreference = IDL.Record({
    'destination' : IDL.Text,
    'bookingId' : IDL.Nat,
    'remind7Days' : IDL.Bool,
    'userId' : IDL.Text,
    'travelDate' : IDL.Text,
    'remind3Days' : IDL.Bool,
    'remind1Day' : IDL.Bool,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'userName' : IDL.Text,
    'userId' : IDL.Text,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'placeId' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const BudgetEntry = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'currency' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const SurprisePlanEntry = IDL.Record({
    'destination' : IDL.Text,
    'code' : IDL.Text,
    'cost' : IDL.Float64,
    'days' : IDL.Nat,
    'occasion' : IDL.Text,
    'itinerary' : IDL.Vec(IDL.Text),
    'decorations' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'cancelBooking' : IDL.Func([IDL.Nat, IDL.Text], [CancellationResult], []),
    'clearNotificationHistory' : IDL.Func([IDL.Text], [], []),
    'createBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteBudgetEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'fetchAndCacheCurrencyRates' : IDL.Func([], [], []),
    'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(BookingEntry)], ['query']),
    'getCurrencyRates' : IDL.Func([], [IDL.Opt(CurrencyRateCache)], ['query']),
    'getDestination' : IDL.Func([IDL.Text], [IDL.Opt(Destination)], ['query']),
    'getNotificationHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(NotificationHistory)],
        ['query'],
      ),
    'getNotificationPreferences' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(NotificationPreference)],
        ['query'],
      ),
    'getReviewsForPlace' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'getUserBudgetEntries' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BudgetEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Opt(
            IDL.Record({
              'name' : IDL.Text,
              'createdAt' : IDL.Int,
              'email' : IDL.Text,
              'lastLogin' : IDL.Int,
            })
          ),
        ],
        ['query'],
      ),
    'getUserSalt' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'initDestination' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Float64,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'initSurprisePlan' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'listAllDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
    'listUserBookings' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BookingEntry)],
        ['query'],
      ),
    'logNotificationFired' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'loginUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'userId' : IDL.Text,
              'name' : IDL.Text,
              'email' : IDL.Text,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'saveBudgetEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveNotificationPreference' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'saveReview' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'searchDestinations' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Destination)],
        ['query'],
      ),
    'updateCurrencyRates' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)), IDL.Int],
        [],
        [],
      ),
    'validateSurprisePlanCode' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SurprisePlanEntry)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };