/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface NotificationHistory {
    id: bigint;
    destination: string;
    bookingId: bigint;
    userId: string;
    firedAt: bigint;
    reminderType: string;
    message: string;
}
export interface NotificationPreference {
    destination: string;
    bookingId: bigint;
    remind7Days: boolean;
    userId: string;
    travelDate: string;
    remind3Days: boolean;
    remind1Day: boolean;
}
export interface Destination {
    id: string;
    region: string;
    country: string;
    name: string;
    tags: Array<string>;
    pricePerPerson: number;
    description: string;
    image: string;
}
export interface CancellationResult {
    refundAmount: number;
    refundPercentage: bigint;
    message: string;
    success: boolean;
}
export interface BookingEntry {
    id: bigint;
    status: BookingStatus;
    destination: string;
    surprisePlanCode?: string;
    cancellationReason?: string;
    userId: string;
    days: bigint;
    createdAt: bigint;
    totalCost: number;
    travelers: bigint;
    cancelledAt?: bigint;
    bookingType: string;
    paymentRef: string;
    startDate: string;
}
export interface CurrencyRateCache {
    lastUpdated: bigint;
    rates: Array<[string, number]>;
}
export interface BudgetEntry {
    id: bigint;
    userId: string;
    date: string;
    createdAt: bigint;
    description: string;
    currency: string;
    category: string;
    amount: number;
}
export interface Review {
    id: bigint;
    userName: string;
    userId: string;
    createdAt: bigint;
    text: string;
    placeId: string;
    rating: bigint;
}
export interface SurprisePlanEntry {
    destination: string;
    code: string;
    cost: number;
    days: bigint;
    occasion: string;
    itinerary: Array<string>;
    decorations: Array<string>;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export interface backendInterface {
    cancelBooking(id: bigint, reason: string): Promise<CancellationResult>;
    clearNotificationHistory(userId: string): Promise<void>;
    createBooking(userId: string, bookingType: string, destination: string, travelers: bigint, days: bigint, startDate: string, totalCost: number, paymentRef: string, surprisePlanCode: string | null): Promise<bigint>;
    deleteBudgetEntry(id: bigint): Promise<boolean>;
    fetchAndCacheCurrencyRates(): Promise<void>;
    getBooking(id: bigint): Promise<BookingEntry | null>;
    getCurrencyRates(): Promise<CurrencyRateCache | null>;
    getDestination(id: string): Promise<Destination | null>;
    getNotificationHistory(userId: string): Promise<Array<NotificationHistory>>;
    getNotificationPreferences(userId: string): Promise<Array<NotificationPreference>>;
    getReviewsForPlace(placeId: string): Promise<Array<Review>>;
    getUserBudgetEntries(userId: string): Promise<Array<BudgetEntry>>;
    getUserProfile(userId: bigint): Promise<{
        name: string;
        createdAt: bigint;
        email: string;
        lastLogin: bigint;
    } | null>;
    getUserSalt(email: string): Promise<string | null>;
    initDestination(id: string, name: string, country: string, region: string, tags: Array<string>, pricePerPerson: number, image: string, description: string): Promise<void>;
    initSurprisePlan(code: string, destination: string, occasion: string, cost: number, days: bigint, itinerary: Array<string>, decorations: Array<string>): Promise<void>;
    listAllDestinations(): Promise<Array<Destination>>;
    listUserBookings(userId: string): Promise<Array<BookingEntry>>;
    logNotificationFired(userId: string, bookingId: bigint, destination: string, reminderType: string, message: string): Promise<bigint>;
    loginUser(email: string, passwordHash: string): Promise<{
        __kind__: "ok";
        ok: {
            userId: string;
            name: string;
            email: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
    registerUser(name: string, email: string, passwordHash: string, salt: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    saveBudgetEntry(userId: string, category: string, description: string, amount: number, currency: string, date: string): Promise<bigint>;
    saveNotificationPreference(userId: string, bookingId: bigint, destination: string, travelDate: string, remind7Days: boolean, remind3Days: boolean, remind1Day: boolean): Promise<bigint>;
    saveReview(placeId: string, userId: string, userName: string, rating: bigint, reviewText: string): Promise<bigint>;
    searchDestinations(searchTerm: string): Promise<Array<Destination>>;
    updateCurrencyRates(rates: Array<[string, number]>, timestamp: bigint): Promise<void>;
    validateSurprisePlanCode(code: string): Promise<SurprisePlanEntry | null>;
}
import type { BookingEntry as _BookingEntry, BookingStatus as _BookingStatus, CurrencyRateCache as _CurrencyRateCache, Destination as _Destination, SurprisePlanEntry as _SurprisePlanEntry } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async cancelBooking(arg0: bigint, arg1: string): Promise<CancellationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0, arg1);
            return result;
        }
    }
    async clearNotificationHistory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearNotificationHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearNotificationHistory(arg0);
            return result;
        }
    }
    async createBooking(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: string, arg6: number, arg7: string, arg8: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
    async deleteBudgetEntry(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBudgetEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBudgetEntry(arg0);
            return result;
        }
    }
    async fetchAndCacheCurrencyRates(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchAndCacheCurrencyRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchAndCacheCurrencyRates();
            return result;
        }
    }
    async getBooking(arg0: bigint): Promise<BookingEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrencyRates(): Promise<CurrencyRateCache | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrencyRates();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrencyRates();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDestination(arg0: string): Promise<Destination | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDestination(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDestination(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotificationHistory(arg0: string): Promise<Array<NotificationHistory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationHistory(arg0);
            return result;
        }
    }
    async getNotificationPreferences(arg0: string): Promise<Array<NotificationPreference>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationPreferences(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationPreferences(arg0);
            return result;
        }
    }
    async getReviewsForPlace(arg0: string): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewsForPlace(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewsForPlace(arg0);
            return result;
        }
    }
    async getUserBudgetEntries(arg0: string): Promise<Array<BudgetEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBudgetEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBudgetEntries(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: bigint): Promise<{
        name: string;
        createdAt: bigint;
        email: string;
        lastLogin: bigint;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSalt(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSalt(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSalt(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async initDestination(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<string>, arg5: number, arg6: string, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initDestination(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initDestination(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async initSurprisePlan(arg0: string, arg1: string, arg2: string, arg3: number, arg4: bigint, arg5: Array<string>, arg6: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initSurprisePlan(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initSurprisePlan(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async listAllDestinations(): Promise<Array<Destination>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllDestinations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllDestinations();
            return result;
        }
    }
    async listUserBookings(arg0: string): Promise<Array<BookingEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUserBookings(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUserBookings(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async logNotificationFired(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.logNotificationFired(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logNotificationFired(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async loginUser(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: {
            userId: string;
            name: string;
            email: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUser(arg0, arg1);
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUser(arg0, arg1);
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string, arg3: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2, arg3);
                return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2, arg3);
            return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveBudgetEntry(arg0: string, arg1: string, arg2: string, arg3: number, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBudgetEntry(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBudgetEntry(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async saveNotificationPreference(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: boolean, arg5: boolean, arg6: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveNotificationPreference(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveNotificationPreference(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async saveReview(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveReview(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveReview(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async searchDestinations(arg0: string): Promise<Array<Destination>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchDestinations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchDestinations(arg0);
            return result;
        }
    }
    async updateCurrencyRates(arg0: Array<[string, number]>, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCurrencyRates(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCurrencyRates(arg0, arg1);
            return result;
        }
    }
    async validateSurprisePlanCode(arg0: string): Promise<SurprisePlanEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.validateSurprisePlanCode(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateSurprisePlanCode(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BookingEntry_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingEntry): BookingEntry {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Destination]): Destination | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        name: string;
        createdAt: bigint;
        email: string;
        lastLogin: bigint;
    }]): {
    name: string;
    createdAt: bigint;
    email: string;
    lastLogin: bigint;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SurprisePlanEntry]): SurprisePlanEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BookingEntry]): BookingEntry | null {
    return value.length === 0 ? null : from_candid_BookingEntry_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CurrencyRateCache]): CurrencyRateCache | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    destination: string;
    surprisePlanCode: [] | [string];
    cancellationReason: [] | [string];
    userId: string;
    days: bigint;
    createdAt: bigint;
    totalCost: number;
    travelers: bigint;
    cancelledAt: [] | [bigint];
    bookingType: string;
    paymentRef: string;
    startDate: string;
}): {
    id: bigint;
    status: BookingStatus;
    destination: string;
    surprisePlanCode?: string;
    cancellationReason?: string;
    userId: string;
    days: bigint;
    createdAt: bigint;
    totalCost: number;
    travelers: bigint;
    cancelledAt?: bigint;
    bookingType: string;
    paymentRef: string;
    startDate: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n5(_uploadFile, _downloadFile, value.status),
        destination: value.destination,
        surprisePlanCode: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.surprisePlanCode)),
        cancellationReason: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.cancellationReason)),
        userId: value.userId,
        days: value.days,
        createdAt: value.createdAt,
        totalCost: value.totalCost,
        travelers: value.travelers,
        cancelledAt: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.cancelledAt)),
        bookingType: value.bookingType,
        paymentRef: value.paymentRef,
        startDate: value.startDate
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        userId: string;
        name: string;
        email: string;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        userId: string;
        name: string;
        email: string;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookingEntry>): Array<BookingEntry> {
    return value.map((x)=>from_candid_BookingEntry_n3(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
